name: Main workflow

on:
  push:
    branches: [main]

jobs:
  build-react-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Scan and Build
        run: |
          cd $GITHUB_WORKSPACE/react-projects
          for PROJECT_DIR in $(ls); do
            cd $PROJECT_DIR
            npm install && npm run build && mv dist ../../docs/$PROJECT_DIR &
            echo $PROJECT_DIR scanned
            cd ../
          done
